package br.com.ada.t1322.tecnicasprogramacao.projeto.view;

public enum Operacao {
    CADASTRAR, LISTAR_TODAS, LISTAR_POR_STATUS, LISTAR_POR_DATA, FILTAR_POR_STATUS, FILTRAR_POR_STATUS_NOT, FILTRAR_POR_DATA_GT, FILTRAR_POR_DATA_LT

}
